### ISSUE TITLE
Not able to connect L515 Realsense Lidar to USB 3.1

### ISSUE THREAD

**Issue by TheNemo05** [TheNemo05/realsenseros#1]
Device name: Realsense Lidar Camera L515
Firmware: 01.05.08.01
OS: Ubuntu 20.04
SDK: 2.51.0
Language: ROS
Issuse:

The Realsense Lidar Camera L515 is USB 3.1 enabled device, currently working on USB port USB 2.1, The device is successfully integrated with ROS but some data loss is observed. 
![image](https://user-images.githubusercontent.com/112936249/190850917-7838ca8f-b37e-45dc-a4ed-6a064192e62f.png)

I need to run this device on USB 3.1 port of my laptop, but after connection the USB port/ SDK does not detects the device. 
![image](https://user-images.githubusercontent.com/112936249/190850993-4ea3f9be-bd41-4dd5-8368-9a3cde03db1c.png)

@MartyG-RealSense

**Comment by MartyG-RealSense** [comment]
Hi @TheNemo05  Please try unplugging the micro-sized end of the USB cable from the base of the L515 camera, turning the connector around the opposite way and re-inserting it into the camera base (USB-C cables are two-way insertion at the micro-sized end).   Does doing so enable the camera connection to be detected as USB 3, please?

**Comment by TheNemo05** [comment]
Thank you @MartyG-RealSense it worked, device is now working on USB 3.1 port. But why does it shows device is connected to 2.1 port, even though device is connected to 3.1 port ?
![image](https://user-images.githubusercontent.com/112936249/190852260-fd1f8de7-7fe9-4711-ab15-efc68f4e027d.png)

![image](https://user-images.githubusercontent.com/112936249/190852308-6dbf40fb-7f8e-43bc-ac61-840e8f34aa32.png)

**Comment by MartyG-RealSense** [comment]
Are you using the official 1 meter cable supplied with the camera or your own choice of cable, please?

Please try resetting the camera to see whether it is USB 3 after it resets.  You can do this in the Viewer by going to the 'More' option near the top of the side-panel and selecting **Hardware Reset** from its drop-down menu.

In the RealSense ROS wrapper you can reset at launch by adding **initial_reset:=true** to the end of your roslaunch instruction.

**Comment by TheNemo05** [comment]
I have reset the hardware using both Roslaunch & Viewer. Still same issue.

**Comment by TheNemo05** [comment]
also i am using the cable provided with camera.

**Comment by MartyG-RealSense** [comment]
Is the cable connected directly to a USB 3 port on the computer or to a USB hub?  If the hub is USB 2 then the camera connection could be treated as USB 2.

**Comment by TheNemo05** [comment]
The cable is directly connected to USB 3.1 port of laptop.

**Comment by MartyG-RealSense** [comment]
And it still detects as USB 2 if you unplug the camera from the port, wait a couple of seconds and re-insert it?

The camera should also be inserted into the port with a firm, quick motion, as a slow insertion could cause the camera to be mis-detected as USB 2.

**Comment by TheNemo05** [comment]
tried inserting quick on both sides of ports still no change in USB status.

**Comment by MartyG-RealSense** [comment]
Thanks very much for your patience.  Do you have another computer that you can try the camera on to confirm whether or not it is an issue with the USB ports on your particular computer?

**Comment by TheNemo05** [comment]
i tried connecting a D400 series camera on my USB3.1 port, and its displays status - connected to 3.1 USB port.
Also connected L515 on different computer USB 3.1, it displays connected to 2.1 port. is it possible the is some issue in firmware of L515 ?

**Comment by MartyG-RealSense** [comment]
After going through the diagnostic process in this discussion, it is probable that the L515 camera has a hardware fault that cannot be corrected with software.  You could therefore enquire to the retailer that you purchased the L515 from regarding returning it.

**Comment by TheNemo05** [comment]
Thank you, we can now close this issue
