### ISSUE TITLE
Connect Darknet node to realsense camera node

### ISSUE THREAD

**Issue by TheNemo05** [TheNemo05/realsenseros#3]
Hello there @MartyG-RealSense, I am using YOLO V3 which uses darknet, trying to receive image from Intel realsense L515 camera. How do I connect /darknet node to /camera node as shown in the screenshot. I need to capture my realsense camera image into YOLO.

![rosgraph](https://user-images.githubusercontent.com/112936249/191714638-f1d8db4f-f367-4a49-9d69-f6569aed877b.png)

**Comment by MartyG-RealSense** [comment]
Would it be possible to post your questions on the official librealsense support forum, please?  Thanks!

https://github.com/IntelRealSense/librealsense/issues/
